// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExtractPages(arg1:Array<string>,arg2:string):Promise<Array<main.ProcessResult>>;

export function SelectFiles():Promise<Array<main.FileInfo>>;
