// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractPages(arg1, arg2) {
  return window['go']['main']['App']['ExtractPages'](arg1, arg2);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}
